# Generated by Django 4.2 on 2023-06-11 00:42

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GestionMensajeros', '0001_initial'),
        ('GestionClientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('tipo_trasnporte', models.CharField(max_length=20)),
                ('numero_paquetes', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionClientes.cliente')),
                ('id_mensajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionMensajeros.mensajeros')),
                ('id_sucursal_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_destino', to='GestionClientes.sucursale')),
                ('id_sucursal_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_origen', to='GestionClientes.sucursale')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField()),
                ('foto', cloudinary.models.CloudinaryField(max_length=255, verbose_name='detalles_estado')),
                ('id_estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPedidos.estadopedido')),
                ('id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionPedidos.pedido')),
            ],
        ),
    ]
